language: python
python:
  - "3.6"

install:
  - pip install kodi-addon-checker

# command to run our tests
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then kodi-addon-checker --branch=jarvis; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then kodi-addon-checker --branch=jarvis $(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq); fi'

notifications:
  webhooks: https://www.travisbuddy.com/
  email:
    on_failure: change # default: always
