language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install --use-mirrors xbmcswift2==0.1 beautifulsoup
# command to run tests, e.g. python setup.py test
script: python -m unittest discover

